### ISSUE TITLE
Update to Node.js 16

### ISSUE THREAD

**Issue by OrtooAdam** [jossef/action-set-json-field#6]
Hi. When will you be able to update to Node.js 16 as this is currently showing as warning in Github Actions?

**Comment by cee-money** [comment]
Also curious about this, thanks!

**Comment by henrikra** [comment]
Can you guys make pr about this? Should be fairly simple just edit this line and make a pr: https://github.com/jossef/action-set-json-field/blob/master/action.yml#L19
